### PR TITLE
Port SB Profile Analysis tool from 7.7 in component exchange to 10.6 

### PR DESCRIPTION
**Pull request by JimCAtSB**
Greg B. requested this, and he tested this folk. So probably good to go.

### CODE REVIEW

**Comment by TIBCOjstinton** [comment]
I think you also need to add the sb-profile-analysis module to tibco-streaming-community\components\pom.xml and README.md files as part of this change. The pom.xml change is required for the sample to show in Studio

**Comment by TIBCOjstinton** [comment]
And one small typo in the readme.md  as well: "no mater how you run "  ==> "no matter"

**Comment by TIBCOjstinton** [comment]
The included TestCase.java in the SB_ProfileAnalysis/src/test/java folder doesn't run.

This line doesn't point to a valid module
`
server.loadApp("com.example.sb_profileanalysis.SB_ProfileAnalysis");
`
Since this is a community sample and not fully supported, I think we could just get rid of the TestCase.java file rather than trying to make a useful test.

Full Stack:
`(fragment deploy): 2021-07-14 13:08:26.219000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: -------------------------------------------------------
(fragment deploy): 2021-07-14 13:08:26.220000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout:  T E S T S
(fragment deploy): 2021-07-14 13:08:26.223000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: -------------------------------------------------------
(fragment deploy): 2021-07-14 13:08:26.243000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: Running com.example.sb_profileanalysis.TestCase
(fragment deploy): 2021-07-14 13:08:32.457000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.214 sec <<< FAILURE!
(fragment deploy): 2021-07-14 13:08:32.458000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: com.example.sb_profileanalysis.TestCase  Time elapsed: 0 sec  <<< ERROR!
(fragment deploy): 2021-07-14 13:08:32.459000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: com.streambase.sb.runtime.ModuleNotFoundException: Module "com.example.sb_profileanalysis.SB_ProfileAnalysis" cannot be found
(fragment deploy): 2021-07-14 13:08:32.460000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.streambase.sb.runtime.MultipleModuleResolver.findModule(MultipleModuleResolver.java:91)
(fragment deploy): 2021-07-14 13:08:32.462000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.streambase.sb.runtime.MultipleModuleResolver.findModule(MultipleModuleResolver.java:126)
(fragment deploy): 2021-07-14 13:08:32.462000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.streambase.sb.unittest.internal.embedded.EmbeddedServerManager.loadApp(EmbeddedServerManager.java:493)
(fragment deploy): 2021-07-14 13:08:32.462000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.streambase.sb.unittest.internal.embedded.EmbeddedServerManager.loadApp(EmbeddedServerManager.java:467)
(fragment deploy): 2021-07-14 13:08:32.462000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.streambase.sb.unittest.internal.embedded.EmbeddedServerManager.loadApp(EmbeddedServerManager.java:421)
(fragment deploy): 2021-07-14 13:08:32.463000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.example.sb_profileanalysis.TestCase.setupServer(TestCase.java:48)
(fragment deploy): 2021-07-14 13:08:32.463000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
(fragment deploy): 2021-07-14 13:08:32.463000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
(fragment deploy): 2021-07-14 13:08:32.463000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
(fragment deploy): 2021-07-14 13:08:32.464000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
(fragment deploy): 2021-07-14 13:08:32.464000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
(fragment deploy): 2021-07-14 13:08:32.464000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
(fragment deploy): 2021-07-14 13:08:32.465000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
(fragment deploy): 2021-07-14 13:08:32.465000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
(fragment deploy): 2021-07-14 13:08:32.465000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
(fragment deploy): 2021-07-14 13:08:32.465000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
(fragment deploy): 2021-07-14 13:08:32.466000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
(fragment deploy): 2021-07-14 13:08:32.468000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
(fragment deploy): 2021-07-14 13:08:32.468000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.tibco.ep.buildmavenplugin.surefire.TestSet.execute(TestSet.java:67)
(fragment deploy): 2021-07-14 13:08:32.468000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.tibco.ep.buildmavenplugin.surefire.TestSuite.executeTestSet(TestSuite.java:161)
(fragment deploy): 2021-07-14 13:08:32.468000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.tibco.ep.buildmavenplugin.surefire.TestSuite.execute(TestSuite.java:90)
(fragment deploy): 2021-07-14 13:08:32.468000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
(fragment deploy): 2021-07-14 13:08:32.468000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.tibco.ep.buildmavenplugin.surefire.Runner.main(Runner.java:158)
(fragment deploy): 2021-07-14 13:08:32.468000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
(fragment deploy): 2021-07-14 13:08:32.468000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
(fragment deploy): 2021-07-14 13:08:32.469000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
(fragment deploy): 2021-07-14 13:08:32.469000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
(fragment deploy): 2021-07-14 13:08:32.469000-0600 [41948:main] INFO  com.tibco.ep.dtm.stdout: 	at com.kabira.platform.MainWrapper.invokeMain(MainWrapper.java:51)`

**Comment by JimCAtSB** [comment]
Hey Jon,

Thanks for all the review. I'm on PTO today, so apologies after pinging you
about this -can we hit the pause button?  Actually, if the new adapter pair
turns out to be fit for purpose I guess we can just publish both the
profile and adapter thing together.

Cheers, Jim...

**Comment by JimCAtSB** [comment]
Hi Jon!

 

I made the changes your review indicated. Hopefully we can get a two-fer for this merge – both the sb-profile-analysis and blocker-releaser-adapters projects. Both projects are ready for publishing, modulo any faux-pas I’ve made.

 

Thanks! Jim…

**Comment by TIBCOjstinton** [comment]
Thanks Jim! Will give it a look.

**Comment by TIBCOjstinton** [comment]
@JimCAtSB - A couple items on the blocker-release project so far

1) The LICENSE file contents don't seem to match the exact text/formatting of the BSD 3-Clause License, though the contents itself look close. Was this copied from somewhere else?

2) The blocker-releaser-adapters\src\site\markdown contents appear to be from a "Delay Operator". Maybe this was a copy and not updated yet?

3) ReleaserBeanInfo is missing a Copyright statement.

Other than that, looks good.

For the Profiler, it looks good in 10.6.1 now. I did also try it in 11.0.0 and it's failing to typecheck there due to the com.streambase.sb.operator.sbadmin.SbAdminOperator having the leadership property removed from it. Not sure if there's a good/easy way to make these compatible with one another. This may actually need to be a bug on the SbAdminOperator to be backwards compatible?

**Comment by JimCAtSB** [comment]
Hi Jon,

 

Thanks for the review! See below for actions.

 

1) LICENSE. I copied the delay-operator tree and just hacked it for blocker-releaser. The only thing I changed in the LICENSE file was I updated the copyright date.

 

I see there are a bunch of other LICENSE files identical to the delay-operator too:

 

./ams-client/LICENSE

./bollinger-bands-signaling/LICENSE

./cramer-view/LICENSE

./delay-operator/LICENSE

./dt-schema/LICENSE

./flowershop/LICENSE

./nyc-yellow-cabs-demo/LICENSE

./plane-tracker/LICENSE

./redis-adapter/LICENSE

./sb-ldm-influxdb-tableprovider/LICENSE

./smile-operators/LICENSE

./uxadmin/LICENSE

./wikimedia/LICENSE

 

I’ll update the blocker-releaser-adapters/LICENSE file to be identical to sb-profile-analysis/LICENSE, excepting I’ll update the year to 2021. What about the other 13 LICENSE files – update them too?

 

2) src/site: Yea, I just copied the delay-operator. The community doc <https://confluence.tibco.com/display/EP/TIBCO+Streaming+Community+GitHub+Repository>  doesn’t have anything to say about site doc and other projects have varying stuff in there. I just deleted the src/site directory – is that good enough?

 

3) ReleaserBeanInfo does have TIBCO copyright info. Is it not formatted in a way that is recognized?

 

RE: 11.0 compatibility. Unfortunately, there will be at least several projects that will not typecheck in 11.0. There’s been some APIs changed/removed and apparently some operator changes too. I’m not sure 11.0 is done changing/removing, so I think for now we just accept some projects will need updates to work with 11.0 GA. Not sure if SbAdminOperator needs a bug, or if that should just documented as a known upgrade incompatibility. There should be a jira for one or the other…

 

Thanks, Jim…

**Comment by TIBCOjstinton** [comment]
Thanks @JimCAtSB !

> I’ll update the blocker-releaser-adapters/LICENSE file to be identical to sb-profile-analysis/LICENSE, excepting I’ll update the year to 2021. What about the other 13 LICENSE files – update them too?

Thanks. Didn't notice that. I think it's just a slightly different format. We can leave the old ones as-is and use the newer format going forward.

> 2) src/site: Yea, I just copied the delay-operator. The community doc <https://confluence.tibco.com/display/EP/TIBCO+Streaming+Community+GitHub+Repository>  doesn’t have anything to say about site doc and other projects have varying stuff in there. I just deleted the src/site directory – is that good enough?

That should be fine. The Readme at the root is the important one.

> 3) ReleaserBeanInfo does have TIBCO copyright info. Is it not formatted in a way that is recognized?

Hmmm... I'm not seeing it in GitHub or my local checkout in components/blocker-releaser-adapters/src/main/java/com/tibco/contrib/ReleaserBeanInfo.java

It says line one is the package declaration. https://github.com/TIBCOSoftware/tibco-streaming-community/pull/15/files#diff-bd2a4e09aa3784fae8127093c45524b999a206fdb550c9c74f7abbe43abe123f  Maybe you've got a local change? Or maybe I'm missing something.

**Comment by JimCAtSB** [comment]
Dooh! Yes, ReleaserBeanInfo is missing copyright. I kept checking BlockerBeanInfo… Updated now.

 

Thanks much for the help! Jim…

**Pull request merged**
